"""
Constants used throughout the SOCKS5 proxy implementation.
"""

# Application version constants
APP_VERSION_MAJOR = 0
APP_VERSION_MINOR = 2
APP_VERSION_PATCH = 1
APP_VERSION = f"{APP_VERSION_MAJOR}.{APP_VERSION_MINOR}.{APP_VERSION_PATCH}"

# SOCKS5 protocol constants
SOCKS_VERSION = 5

# SOCKS5 command types
CMD_CONNECT = 1
CMD_BIND = 2
CMD_UDP_ASSOCIATE = 3

# SOCKS5 address types
ATYP_IPV4 = 1
ATYP_DOMAIN = 3
ATYP_IPV6 = 4

# SOCKS5 reply codes
REPLY_SUCCESS = 0
REPLY_GENERAL_FAILURE = 1
REPLY_CONNECTION_NOT_ALLOWED = 2
REPLY_NETWORK_UNREACHABLE = 3
REPLY_HOST_UNREACHABLE = 4
REPLY_CONNECTION_REFUSED = 5
REPLY_TTL_EXPIRED = 6
REPLY_COMMAND_NOT_SUPPORTED = 7
REPLY_ADDRESS_TYPE_NOT_SUPPORTED = 8

# SOCKS5 authentication methods
AUTH_NO_AUTH = 0
AUTH_GSSAPI = 1
AUTH_USERNAME_PASSWORD = 2
AUTH_NO_ACCEPTABLE_METHODS = 255

# Buffer sizes
DEFAULT_BUFFER_SIZE = 4096
MAX_BUFFER_SIZE = 10 * 1024 * 1024
# Logging
DEFAULT_LOGGING_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
